### ISSUE TITLE
pg.types in node-redshift

### ISSUE THREAD

**Issue by Noursounet** [dmanjunath/node-redshift#14]
Hi,

When a date is pulled from RedShift, nodejs makes a "new Date()", so we depend on Local timezone.
pg offers the possibility to override types parsing:
```
var pg = require('pg');
var types = pg.types;

var TIMESTAMP_OID = 1114;
var parseDateFn = function (val) {
    return val === null ? null : val;
};
types.setTypeParser(TIMESTAMP_OID, parseDateFn);
```

Unfortunately the node-redshift npm doesn't export this pg.types object and so we can't modify the way javascript will parse redshift data.

Would it be possible to add it?

Thanks

**Comment by dmanjunath** [comment]
Yeah great suggestion @Noursounet. Turns out it was a one liner to add it to redshift object. I've pushed up the code already. I'll update the readme and I'll do an npm push sometime today.

**Comment by Noursounet** [comment]
Thanks a lot!

**Comment by Noursounet** [comment]
Hi @dmanjunath, 

Sorry for bothering but i was wandering when are you planning to publish the new npm version ? ^^

Thanks a lot!

Noursounet

**Comment by dmanjunath** [comment]
@Noursounet sorry about the delay but I published it about three hours ago! Look for version 0.1.2.

**Comment by Noursounet** [comment]
Great! Thanks a lot
