### ISSUE TITLE
How do I pass multiple records in to create function?

### ISSUE THREAD

**Issue by sfbenedict** [dmanjunath/node-redshift#7]
Can you give an example of passing multiple records in to the create function.

I tried [{'abc':123},{'abc':123}]

Thanks great work!

**Comment by dmanjunath** [comment]
I pushed up a patch that should allow you to pass in an array now with this commit https://github.com/dmanjunath/node-redshift/commit/500071ec91ced0472c13e6625a92ea6309f317ed. I'm working on some other connection issue bugs and adding the next set of features and I'll do a release on npm hopefully by the end of the week. Thanks for the feedback!
